FROM nginx:1.10.1-alpine
COPY . /usr/share/nginx/html
#COPY css . /usr/share/nginx/html/css
#COPY script . /usr/share/nginx/html/script
#COPY Empty.html /usr/share/nginx/html/Empty.html
#COPY index.html /usr/share/nginx/html/index.html
#COPY Time-Calculator.html /usr/share/nginx/html/Time-Calculator.html

# doc
# EXPOSE 80
#CMD ["nginx","-g","daemon off;"]